services:
  db:
    image: postgres:18
    container_name: wtms-db
    ports:
      - "9999:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: hrms-app
#    depends_on:
#      db:
#        condition: service_healthy
#    ports:
#      - "7777:8080"
#    env_file:
#      - .env
#    environment:
#      SPRING_PROFILES_ACTIVE: dev