spring:
  datasource:
    url: jdbc:postgresql://114.29.239.33:5432/wtms
    username: postgres
    password: Postgres@2026
    driver-class-name: org.postgresql.Driver
cloudinary:
  cloud-name: dkloakzs6
  api-key: 162361396439147
  api-secret: DVu7SNnY50pVCr7xxY1mRmsO4Os
